---
- name: "Install dependencies: dnf-plugins-core, yum-utils"
  ansible.builtin.package:
    name: 
      - dnf-plugins-core
      - yum-utils
  become: true
  register: INSTALL_POWERTOOLS
  ignore_errors: true
- name: "Install dependencies: dnf-plugins-core, yum-utils"
  shell: "pkcon install -y {{ item }} | true"
  loop:
    - dnf-plugins-core
    - yum-utils
  when: INSTALL_POWERTOOLS.failed
- name: "Enable powertools repo"
  shell: "yum-config-manager --enable powertools"
  ignore_errors: true
  become: true
  register: ENABLE_POWERTOOLS
- name: "Enable powertools repo"
  shell: "pkcon repo-enable powertools"
  ignore_errors: true
  become: true
  when: ENABLE_POWERTOOLS.failed
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  package:
    name: "{{ APP_DEPENDENCIES }}"
  become: true
  register: INSTALL_DEPENDENCIES
  ignore_errors: true
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ APP_DEPENDENCIES }}"
  when: INSTALL_DEPENDENCIES.failed
- name: "Create the directory {{ APP_SRC }}"
  file:
    name: "{{ APP_SRC }}"
    state: directory
- name: "Check for the README file {{ APP_README }}"
  stat:
    path: "{{ APP_README }}"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO }} source code into {{ APP_SRC }}"
  git:
    repo: "{{ APP_REPO }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists
- name: "Run the svn cleanup in case subversion failed"
  shell:
    cmd: svn cleanup
    chdir: "{{ APP_ASSETS_SRC }}"
  ignore_errors: true
- name: "Clone the stk-assets source code into {{ APP_ASSETS_SRC }}"
  ansible.builtin.subversion:
    repo: "{{ APP_ASSETS_REPO }}"
    dest: "{{ APP_ASSETS_SRC }}"
  ignore_errors: true
- name: "Run the svn cleanup in case subversion failed"
  shell:
    cmd: svn cleanup
    chdir: "{{ APP_ASSETS_SRC }}"
  ignore_errors: true
- name: "Clone the stk-assets source code into {{ APP_ASSETS_SRC }}"
  ansible.builtin.subversion:
    repo: "{{ APP_ASSETS_REPO }}"
    dest: "{{ APP_ASSETS_SRC }}"
  ignore_errors: true
- name: "Run the svn cleanup in case subversion failed"
  shell:
    cmd: svn cleanup
    chdir: "{{ APP_ASSETS_SRC }}"
  ignore_errors: true
- name: "Clone the stk-assets source code into {{ APP_ASSETS_SRC }}"
  ansible.builtin.subversion:
    repo: "{{ APP_ASSETS_REPO }}"
    dest: "{{ APP_ASSETS_SRC }}"
  ignore_errors: true
- name: "Create the directory {{ APP_SRC }}/cmake_build"
  file:
    name: "{{ APP_SRC }}/cmake_build"
    state: directory
- name: "Run the cmake script in {{ APP_SRC }}/cmake_build"
  shell:
    cmd: "cmake ..  -DBUILD_RECORDER=0 -DCMAKE_INSTALL_PREFIX={{ APP_PREFIX }}"
    chdir: "{{ APP_SRC }}/cmake_build"
- name: "Run the make script in {{ APP_SRC }}/cmake_build"
  shell:
    cmd: make
    chdir: "{{ APP_SRC }}/cmake_build"
- name: "Run the make install script in {{ APP_SRC }}/cmake_build"
  shell:
    cmd: make install
    chdir: "{{ APP_SRC }}/cmake_build"
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"

